### ISSUE TITLE
你能尝试编译出mac下的shadowvpn客户端吗？

### ISSUE THREAD

**Issue by luckypoem** [lixingcong/lixingcong.github.io#1]
hi.
读了你的文章：
http://lixingcong.github.io/2015/12/17/shadowvpn-conf-lixingcongv2/ ，你能尝试编译出mac下的shadowvpn客户端吗？

**Comment by lixingcong** [comment]
不清楚，我看官网的readme他说的支持OSX系统。但是我没有苹果
