### ISSUE TITLE
微信 SightDraftInfo 表

### ISSUE THREAD

**Issue by summerwxy** [lixingcong/lixingcong.github.io#2]
你好

我想问问你哪里有没有 SightDraftInfo 表的相关资料可以参考

我试了几个方法， 还是没有办法替代影片

微信版本是最新的 6.3.23

**Comment by lixingcong** [comment]
貌似新版改了表，老方法实效了。。我没兴趣捣鼓了这玩意。。可以自己折腾下

**Comment by summerwxy** [comment]
好吧， 谢谢了

有个 fileNameHash 我查了反编译的 apk，没看懂

放弃好了。
